#For description of parameter please do refer to Readme.txt
version: '3.3'
services:
  rcs:
    image: contentserver_ubuntu:16.4.0000.0248
    environment:
      - DOCKER_HOST=10.0.75.1
      - DATABASE_HOST=postgres_dctm
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_SERVER_PORT=5432
      - ROOT_PASSWORD=password
      - INSTALL_OWNER=dmadmin
      - INSTALL_OWNER_PASSWORD=password
      - DOCBASE_NAME=DocbaseName
      - GLOBAL_REGISTRY_PASSWORD=password
      - AEK_ALGORITHM=AES_256_CBC
      - AEK_PASSPHRASE=password
      - AEK_NAME=CSaek
      - ENABLE_LOCKBOX=true
      - LOCKBOX_FILE_NAME=lockbox.lb
      - LOCKBOX_PASSPHRASE=Password@123
      - CONFIGURE_THUMBNAIL_SERVER=NO
      - THUMBNAIL_SERVER_PORT=8081
      - THUMBNAIL_SERVER_SSL_PORT=8443
      - EXTERNAL_DOCBROKER_PORT=1689
      - CONTENTSERVER_PORT=50000
      - APP_SERVER_PASSWORD=jboss
      - INSTALL_OWNER_UID=1000
      - HIGH_VOLUME_SERVER_LICENSE=
      - TRUSTED_LICENSE=
      - STORAGEAWARE_LICENSE=
      - XMLSTORE_LICENSE=
      - SNAPLOCKSTORE_LICENSE=
      - RPS_LICENSE=
      - FED_RECD_SERVICE_LICENSE=
      - RECORD_MANAGER_LICENSE=
      - PRM_LICENSE=
      - DOCBASE_PASSWORD=password
      - INSTALLER_UI=silent
      - KEEP_TEMP_FILE=false
      - INSTALLER_DEBUG_LOG=true
      - DOCBASE_ID=453216
      - USE_EXISTING_DATABASE_ACCOUNT=
      - INDEXSPACE_NAME=DM_XCHIVE_DOCBASE
      - USE_EXISTING_AEK_LOCKBOX=false
    hostname:
      "cs_host"
    container_name:
      "documentumcs"
    ports:
      - "1489:1489"
      - "1490:1490"
      - "1689:1689"
      - "1690:1690"
      - "50000:50000"
      - "50001:50001"
      - "9080:9080"
      - "9082:9082"
      - "9081:9081"
      - "9084:9084"
      - "8081:8081"
      - "8443:8443"
    volumes:
      - DocbaseName_odbc:/opt/dctm/odbc
      - DocbaseName_data:/opt/dctm/data
      - DocbaseName_dba:/opt/dctm/dba
      - DocbaseName_share:/opt/dctm/share
      - DocbaseName_dfc:/opt/dctm/config
      - DocbaseName_mdserver_conf:/opt/dctm/mdserver_conf
      - DocbaseName_mdserver_log:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/log
      - DocbaseName_mdserver_logs:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/logs
      - DocbaseName_Thumbnail_Server_conf:/opt/dctm/product/16.4/thumbsrv/conf
      - DocbaseName_Thumbnail_Server_webinf:/opt/dctm/product/16.4/thumbsrv/container/webapps/thumbsrv/WEB-INF
      - DocbaseName_xhive_storage:/opt/dctm/xhive_storage
      - DocbaseName_XhiveConnector:/opt/dctm/wildfly9.0.1/server/DctmServer_MethodServer/deployments/XhiveConnector.ear
    privileged: true
#'volumes' service definition: 
volumes:
 DocbaseName_data:
 DocbaseName_share:
 DocbaseName_dba:
 DocbaseName_dfc:
 DocbaseName_odbc:
 DocbaseName_mdserver_conf:
 DocbaseName_mdserver_log:
 DocbaseName_mdserver_logs:
 DocbaseName_Thumbnail_Server_conf:
 DocbaseName_Thumbnail_Server_webinf:
 DocbaseName_XhiveConnector:
 DocbaseName_xhive_storage:
networks:
  default:
    external:
      name: postgres-network
